export const getProjectData = () => {
	return [
		{
			name: 'Palette Picker',
			gitHub: 'https://github.com/davidbecker6081/PalettePicker',
			imageUrl: 'https://i.imgur.com/7X99IEX.png',
			technologies: ['Javascript', 'JQuery', 'PostgreSQL', 'Express', 'Knex'],
			testing: 'Mocha/Chai, chai-http',
			dateCompleted: 'October 6, 2017',
		},
		{
			name: 'ConnectME',
			gitHub: 'https://github.com/davidbecker6081/ConnectME',
			imageUrl: 'https://i.imgur.com/E4aPHt0.png',
			technologies: ['React', 'Redux', 'Firebase OAuth/Database', 'React Router'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'September 20, 2017',
		},
		{
			name: 'MovieTracker',
			gitHub: 'https://github.com/davidbecker6081/movie-tracker',
			imageUrl: 'https://i.imgur.com/EQ0uUzp.png',
			technologies: ['React', 'Redux', 'React Router', 'PostgreSQL'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'September 7, 2017',
		},
		{
			name: 'SWAPI-Box',
			gitHub: 'https://github.com/davidbecker6081/SWAPI-Box',
			imageUrl: 'https://i.imgur.com/dFlmnE6.png',
			technologies: ['React', 'React Router'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'August 24, 2017',
		},
		{
			name: 'Weathrly',
			gitHub: 'https://github.com/davidbecker6081/weathrly',
			imageUrl: 'https://i.imgur.com/F3v02xi.png',
			technologies: ['React', 'HTML5', 'CSS3'],
			testing: 'Enzyme/Jest',
			dateCompleted: 'August 3, 2017',
		},
		{
			name: 'TRON',
			gitHub: 'https://github.com/jackmallahan/game-time',
			imageUrl: 'https://i.imgur.com/7R2T3TV.png',
			technologies: ['HTML5', 'CSS3', 'JavaScript', 'HTML5 Canvas'],
			testing: 'Mocha/Chai',
			dateCompleted: 'July 20, 2017',
		},
		// {
		// 	name: 'Static Comp 3',
		// 	gitHub: 'https://github.com/davidbecker6081/DB-comp-challenge-3',
		// 	imageUrl: 'https://i.imgur.com/xhRDOKi.png',
		// 	technologies: ['HTML5', 'CSS3'],
		// 	testing: 'N/A',
		// 	dateCompleted: 'June 6, 2017',
		// },
		// {
		// 	name: 'MovieTracker',
		// 	gitHub: 'www.github.com/2',
		// 	imageUrl: 'www.image.com/2',
		// 	technologies: ['React', 'Redux', 'MomentJS', 'React Router', 'HTML5 Canvas'],
		// 	testing: '',
		// 	dateCompleted: 'September 20, 2017',
		// },
		// {
		// 	name: 'MovieTracker',
		// 	gitHub: 'www.github.com/2',
		// 	imageUrl: 'www.image.com/2',
		// 	technologies: ['React', 'Redux', 'MomentJS', 'React Router', 'HTML5 Canvas'],
		// 	testing: '',
		// 	dateCompleted: 'September 20, 2017',
		// },
	];
};
