export const getProjectData = () => {
	return [
		{
			name: 'ConnectME',
			about: 'I wanted to create an application that streamlined a few functionalities that Facebook already provided, but in a rather user-unfriendly way. The goal was to create a platform to search friends in a particular location and then message one particular friend or a group of friends in that location. A user should be able to login and logout, send and store messages to and from friends, and eventually, store groups of friends in particular locations. In this project, I implemented Firebase OAuth and database, used the Facebook Graph API, and tested with Enzyme/Jest.',
			gitHub: 'https://github.com/davidbecker6081/ConnectME',
			liveLink: '',
			imageUrl: 'https://i.imgur.com/E4aPHt0.png',
			technologies: ['React', 'Redux', 'React Router', 'Firebase OAuth/Database'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'September 20, 2017',
		},
		{
			name: 'BYOB',
			about: '',
			gitHub: 'https://github.com/davidbecker6081/BYOB',
			liveLink: 'https://byob-db-th.herokuapp.com/',
			imageUrl: 'https://i.imgur.com/VT38K9D.png',
			technologies: ['Javascript', 'JQuery', 'PostgreSQL', 'Express', 'Knex'],
			testing: 'Mocha/Chai, chai-http',
			dateCompleted: 'October 6, 2017',
		},
		{
			name: 'MovieTracker',
			about: '',
			gitHub: 'https://github.com/davidbecker6081/movie-tracker',
			liveLink: '',
			imageUrl: 'https://i.imgur.com/EQ0uUzp.png',
			technologies: ['React', 'Redux', 'React Router', 'PostgreSQL'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'September 7, 2017',
		},
		{
			name: 'SWAPI-Box',
			about: '',
			gitHub: 'https://github.com/davidbecker6081/SWAPI-Box',
			liveLink: '',
			imageUrl: 'https://i.imgur.com/dFlmnE6.png',
			technologies: ['React', 'React Router'],
			testing: 'Enzyme/Jest, fetch-mock',
			dateCompleted: 'August 24, 2017',
		},
		{
			name: 'Weathrly',
			about: '',
			gitHub: 'https://github.com/davidbecker6081/weathrly',
			liveLink: '',
			imageUrl: 'https://i.imgur.com/F3v02xi.png',
			technologies: ['React', 'HTML5', 'CSS3'],
			testing: 'Enzyme/Jest',
			dateCompleted: 'August 3, 2017',
		},
		{
			name: 'TRON',
			about: '',
			gitHub: 'https://github.com/jackmallahan/game-time',
			liveLink: '',
			imageUrl: 'https://i.imgur.com/7R2T3TV.png',
			technologies: ['HTML5', 'CSS3', 'JavaScript', 'HTML5 Canvas'],
			testing: 'Mocha/Chai',
			dateCompleted: 'July 20, 2017',
		},
		// {
		// 	name: 'Static Comp 3',
		// 	gitHub: 'https://github.com/davidbecker6081/DB-comp-challenge-3',
		// 	imageUrl: 'https://i.imgur.com/xhRDOKi.png',
		// 	technologies: ['HTML5', 'CSS3'],
		// 	testing: 'N/A',
		// 	dateCompleted: 'June 6, 2017',
		// },
		// {
		// 	name: 'MovieTracker',
		// 	gitHub: 'www.github.com/2',
		// 	imageUrl: 'www.image.com/2',
		// 	technologies: ['React', 'Redux', 'MomentJS', 'React Router', 'HTML5 Canvas'],
		// 	testing: '',
		// 	dateCompleted: 'September 20, 2017',
		// },
		// {
		// 	name: 'MovieTracker',
		// 	gitHub: 'www.github.com/2',
		// 	imageUrl: 'www.image.com/2',
		// 	technologies: ['React', 'Redux', 'MomentJS', 'React Router', 'HTML5 Canvas'],
		// 	testing: '',
		// 	dateCompleted: 'September 20, 2017',
		// },
	];
};
